import LenisProvider from './provider/lenis-provider'
import "./globals.css";
import NavWrapper from "./NavWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavWrapper />
        <LenisProvider>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
