
"use client";
import "./globals.css";
import { useState } from "react";
import Nav from "../components/Nav";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
       <Nav isMenuOpen={isMenuOpen} setIsMenuOpen={setIsMenuOpen} />
        {children}
      </body>
    </html>
  );
}
